spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: root
    password: root
    driverClassName: org.h2.Driver
  security:
    user:
      name: ibrah
      password: azerty
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

